routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\BankSekolahController;
use App\Http\Controllers\BerandaOperatorController;
use App\Http\Controllers\BerandaWaliController;
use App\Http\Controllers\BiayaController;
use App\Http\Controllers\KartuSppController;
use App\Http\Controllers\KwitansiPembayaranController;
use App\Http\Controllers\PanduanPembayaranController;
use App\Http\Controllers\PembayaranController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\SiswaController;
use App\Http\Controllers\StatusController;
use App\Http\Controllers\TagihanController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WaliController;
use App\Http\Controllers\WaliMuridInvoiceController;
use App\Http\Controllers\WaliMuridPembayaranController;
use App\Http\Controllers\WaliMuridProfilController;
use App\Http\Controllers\WaliMuridSiswaController;
use App\Http\Controllers\WaliMuridTagihanController;
use App\Http\Controllers\WaliSiswaController;
use App\Models\BankSekolah;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;





/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('tes', function () {
//     echo  $url = URL::temporarySignedRoute(
//         'login.url',
//         now()->addDays(10),
//         [
//             'pembayaran_id' => 1,
//             'user_id' => 1,
//             'url' => route('pembayaran.show', 1)
//         ]
//     );
// });

Route::get('login/login-url', [LoginController::class, 'loginUrl'])->name('login.url');
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('panduan-pembayaran/{id}', [PanduanPembayaranController::class, 'index'])->name('panduan.pembayaran');

Route::prefix('operator')->middleware(['auth', 'auth.operator'])->group(function () {
    //ini route khusus untuk operator
    Route::get('beranda', [BerandaOperatorController::class, 'index'])->name('operator.beranda');
    Route::resource('banksekolah', BankSekolahController::class);
    Route::resource('user', UserController::class);
    Route::resource('wali', WaliController::class);
    Route::resource('siswa', SiswaController::class);
    Route::resource('walisiswa', WaliSiswaController::class);
    Route::resource('biaya', BiayaController::class);
    Route::resource('tagihan', TagihanController::class);
    Route::resource('pembayaran', PembayaranController::class);
    Route::resource('setting', SettingController::class);
    Route::get('kwitansi-pembayaran/{id}', [KwitansiPembayaranController::class, 'show'])->name('kwitansipembayaran.show');
    Route::get('kartuspp', [KartuSppController::class, 'index'])->name('kartuspp.index');
    Route::get('delete-biaya-item/{id}', [BiayaController::class, 'deleteItem'])->name('delete-biaya.item');
    Route::get('status/update', [StatusController::class, 'update'])->name('status.update');
});

Route::prefix('walimurid')->middleware(['auth', 'auth.wali'])->name('wali.')->group(function () {
    //ini route khusus untuk wali-murid
    Route::get('beranda', [BerandaWaliController::class, 'index'])->name('beranda');
    Route::resource('siswa', WaliMuridSiswaController::class);
    Route::resource('tagihan', WaliMuridTagihanController::class);
    Route::resource('pembayaran', WaliMuridPembayaranController::class);
    Route::resource('profil', WaliMuridProfilController::class);
    Route::resource('invoice', WaliMuridInvoiceController::class);
});

Route::prefix('admin')->middleware(['auth', 'auth.admin'])->group(function () {
    //ini route khusus untuk admin
});




Route::get('logout', function () {
    Auth::logout();
    return redirect('/login');
})->name('logout');



Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/operator/banksekolah_form.blade.php
@extends('layouts.app_sneat')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ $title }}</div>
                <div class="card-body">
                    {!! Form::model($model, 
                        ['route' => $route, 
                        'method' => $method
                    ]) !!}
                    
                    <div class="form-group mt-1">
                        <lable for="nama">Nama Bank</lable>
                        {!! Form::select('bank_id', $listBank, null, ['class' => 'form-control select2' ]) !!}
                        <span class="text-danger">{{ $errors->first('bank_id') }}</span>
                    </div>
                    
                    <div class="form-group mt-3">
                        <lable for="nama_rekening">Nama Pemilik Rekening</lable>
                        {!! Form::text('nama_rekening', null, ['class' => 'form-control']) !!}
                        <span class="text-danger">{{ $errors->first('nama_rekening') }}</span>
                    </div>

                    <div class="form-group mt-3">
                        <lable for="nomor_rekening">Nomor Rekening</lable>
                        {!! Form::text('nomor_rekening', null, ['class' => 'form-control']) !!}
                        <span class="text-danger">{{ $errors->first('nomor_rekening') }}</span>
                    </div>

                    {!! Form::submit($button, ['class' => 'btn btn-primary mt-3']) !!}
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/operator/banksekolah_index.blade.php
@extends('layouts.app_sneat')

@section('content')
    <div class="row justify-content-center">
        <h4 class="fw-bold py-1 mb-4">{{ $title }}</h4>
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <a href="{{ route($routePrefix . '.create') }}" class="btn btn-primary ">Tambah Data</a>
                    <div class="table-responsive mt-3">
                        <table class="{{ config('app.table_style') }}">
                            <thead class="{{ config('app.thead_style') }}">
                                <tr>
                                    <th>No</th>
                                    <th>Nama Bank</th>
                                    <th>Kode transfer</th>
                                    <th>pemilik rekening</th>
                                    <th>nomor rekening</th>
                                    <th style="text-align:center">Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($models as $item)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $item->nama_bank}}</td>
                                        <td>{{ $item->kode }}</td>
                                        <td>{{ $item->nama_rekening }}</td>
                                        <td>{{ $item->nomor_rekening }}</td>
                                        <td style="text-align:center">
                                            {!! Form::open([
                                                'route' => [$routePrefix . '.destroy', $item->id],
                                                'method' => 'DELETE',
                                                'onsubmit' => 'return confirm("Yakin ingin menghapus data ini?")',
                                            ]) !!}
                                            <a href="{{ route($routePrefix . '.edit', $item->id) }}"
                                                class="btn btn-warning btn-sm">
                                                <i class="fa fa-edit"></i>&emsp;Edit
                                            </a>
                                            <button type="submit" class="btn btn-danger btn-sm"><i
                                                    class="fa fa-trash"></i>&emsp;Hapus</button>
                                            {!! Form::close() !!}
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="8" style="text-align: center">Data tidak ada</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                        {!! $models->links() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/operator/beranda_index.blade.php
@extends('layouts.app_sneat', ['title' => 'Beranda Operator'])

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <h5 class="card-header">{{ $title }}</h5>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/operator/biaya_form.blade.php
@extends('layouts.app_sneat')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <h5 class="card-header" >{{ $title }}</h5>
                <div class="card-body">
                    {!! Form::model($model, [
                        'route' => $route, 
                        'method' => $method
                    ]) !!}
                    @if (request()->filled('parent_id'))
                        <h3>INFO {{ $parentData->nama }}</h3>
                        {!! Form::hidden('parent_id', $parentData->id, []) !!}
                        <div class="container">
                            <div class="col-md-6">
                                <table class="table table-sm table-hover table-bordered" >
                                    <thead>
                                        <tr>
                                            <td>Parent ID</td>
                                            <td>Nama Biaya</td>
                                            <td>Jumlah</td>
                                            <td>Aksi</td>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($parentData->children as $item)
                                            <tr>
                                                <td>{{ $loop->iteration }}</td>
                                                <td>{{ $item->nama }}</td>
                                                <td>{{ formatRupiah($item->jumlah) }}</td>
                                                <td>
                                                    <a href="{{ route('delete-biaya.item', $item->id) }}" class="btn btn-danger btn-sm" onclick="return confirm('Anda Yakin ?')">
                                                    Hapus
                                                    </a>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    @endif
                    <div class="form-group mt-3">
                        <lable for="nama">Nama Biaya</lable>
                        {!! Form::text('nama', null, ['class' => 'form-control', 'autofocus']) !!}
                        <span class="text-danger">{{ $errors->first('nama') }}</span>
                    </div>
                    <div class="form-group mt-3">
                        <lable for="jumlah">Jumlah / Nominal</lable>
                        {!! Form::text('jumlah', null, ['class' => 'form-control rupiah']) !!}
                        <span class="text-danger">{{ $errors->first('jumlah') }}</span>
                    </div>

                    {!! Form::submit($button, ['class' => 'btn btn-primary mt-3']) !!}
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/operator/biaya_index.blade.php
@extends('layouts.app_sneat')

@section('content')
<div class="row justify-content-center">
    <h4 class="fw-bold py-1 mb-4">{{ $title }}</h4>
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <a href="{{ route($routePrefix . '.create') }}" class="btn btn-primary btn-sm">Tambah Data</a>
                    </div>
                    <div class="col-md-6">
                        {!! Form::open(['route' => $routePrefix . '.index', 'method' => 'GET']) !!}
                            <div class="input-group">
                                <input name="q" type="text" class="form-control" placeholder="Cari Nama Biaya" aria-label="nama biaya" aria-describedby="button-addon2" value="{{ request('q') }}">
                                <button class="btn btn-outline-primary" type="submit" id="button-addon2"><i class="bx bx-search"></i>
                                </button>
                            </div>
                        {!! Form::close() !!}
                    </div>
                    <div class="table-responsive">
                        <table class="table table-striped mb-4">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Nama Biaya</th>
                                    <th>Total Tagihan</th>
                                    <th>Created By</th>
                                    <th style="text-align:center">Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($models as $item)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $item->nama }}</td>
                                        <td>{{ formatRupiah($item->total_tagihan) }}</td>
                                        <td>{{ $item->user->name }}</td>
                                        <td style="text-align:center">
                                            {!! Form::open([
                                                'route' => [$routePrefix . '.destroy', $item->id],
                                                'method' => 'DELETE',
                                                'onsubmit' => 'return confirm("Yakin ingin menghapus data ini?")',
                                            ]) !!}
                                            <a href="{{ route($routePrefix . '.edit', $item->id) }}"
                                                class="btn btn-warning btn-sm">
                                                <i class="fa fa-edit"></i>&emsp;Edit
                                            </a>
                                            <a href="{{ route($routePrefix . '.create', [
                                                'parent_id' =>$item->id,
                                            ]) }}"
                                                class="btn btn-info btn-sm mx-2">
                                                <i class="fa fa-edit"></i>&emsp;Item
                                            </a>
                                            <button type="submit" class="btn btn-danger btn-sm"><i
                                                    class="fa fa-trash"></i>&emsp;Hapus</button>
                                            {!! Form::close() !!}
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="8" style="text-align: center">Data tidak ada</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                        {!! $models->links() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/operator/kwitansi_pembayaran.blade.php
@extends('layouts.app_sneat_blank')
@section('content')
<script type="text/javascript">
    window.print();
</script>
    <div class="container mt-5">
        <div class="d-flex justify-content-center row">
            <div class="col-md-8">
                <div class="p-3 bg-white rounded">
                    <div class="row">
                        <div class="col-md-12">
                            <h1 class="text-uppercase">KWITANSI PEMBAYARAN</h1>
                            <div class="billed"><span class="font-weight-bold ">Nama Sekolah :</span><span class="ml-1"> SDN
                                    02 SELO</span></div>
                            <div class="billed"><span class="font-weight-bold ">Tanggal Tagihan :</span><span
                                    class="ml-1"> {{ $pembayaran->tanggal_bayar->translatedFormat('d F Y') }}</span></div>
                            <div class="billed"><span class="font-weight-bold ">Pembayaran ID :</span><span class="ml-1">
                                    #SDUS - {{ $pembayaran->id }}</span></div>
                        </div>
                    </div>
                    <div class="mt-3">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Tanggal Pembayaran</th>
                                        <th>Metode Bayar</th>
                                        <th>Jumlah Pembayaran</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>{{ $pembayaran->tanggal_bayar->translatedFormat('d/m/Y') }}</td>
                                        <td>{{ formatRupiah($pembayaran->jumlah_dibayar) }}</td>
                                        <td>{{ $pembayaran->metode_pembayaran }}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="text-right mb-3">
                      <i>Terbilang : {{ ucwords(terbilang($pembayaran->jumlah_dibayar)) }} Rupiah </i>
                    </div>

                Semarang, {{ $pembayaran->tanggal_bayar->translatedFormat('d F Y') }}
                <br />
                <br />
                <br />
                <u>{{ $pembayaran->user->name }}</u>
            </div>
            </div>
        </div>
    </div>
@endsection

resources/views/operator/pembayaran_index.blade.php
@extends('layouts.app_sneat')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">DATA PEMBAYARAN</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            {!! Form::open(['route' => 'pembayaran.index', 'method' => 'GET']) !!}
                            <div class="row">
                                <div class="col-md-4 col-sm-12 mt-1">
                                    {!! Form::selectMonth('bulan', request('bulan'), ['class' => 'form-control']) !!}
                                </div>
                                <div class="col-md-4 col-sm-12 mt-1">
                                    {!! Form::selectRange('tahun', 2022, date('Y') + 1, request('tahun') , ['class' => 'form-control']) !!}
                                </div>
                                <div class="col-md-4 col-sm-12 mt-1">
                                    <button class="btn btn-primary" type="submit">Tampil</button>
                                </div>
                            </div>
                            {!! Form::close() !!}
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-striped mb-4">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>NISN</th>
                                    <th>Nama</th>
                                    <th>Nama Wali</th>
                                    <th>Metode Pembayaran</th>
                                    <th>Status Konfirmasi</th>
                                    <th>Tanggal Konfirmmasi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($models as $item)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $item->tagihan->siswa->nisn }}</td>
                                        <td>{{ $item->tagihan->siswa->nama }}</td>
                                        <td>{{ $item->wali->name}}</td>
                                        <td>{{ $item->metode_pembayaran }}</td>
                                        <td>{{ $item->status_konfirmasi }}</td>
                                        <td>
                                            {!! Form::open([
                                                'route' => ['pembayaran.destroy', $item->id],
                                                'method' => 'DELETE',
                                                'onsubmit' => 'return confirm("Yakin ingin menghapus data ini?")',
                                            ]) !!}
                                            <a href="{{ route('pembayaran.show', 
                                                $item->id )  }}" 
                                                class="btn btn-info btn-sm mx-3">
                                                <i class="fa fa-edit"></i> Detail
                                            </a>
                                            <button type="submit" class="btn btn-danger btn-sm"><i
                                                    class="fa fa-trash"></i>&emsp;Hapus</button>
                                            {!! Form::close() !!}
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="8" style="text-align: center">Data tidak ada</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                        {!! $models->links() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/operator/setting_form.blade.php
@extends('layouts.app_sneat', ['title' => 'Pengaturan App'])

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <h5 class="card-header" >Pengaturan Aplikasi</h5>
                <div class="card-body">
                    {!! Form::open([
                        'route' => 'setting.store',
                        'method' => 'POST',
                        ]) !!}
                    <h6>Pengaturan Instansi</h6>
                    <div class="form-group mt-3">
                        <lable for="app_name">Nama Instansi</lable>
                        {!! Form::text('app_name', settings()->get('app_name'), ['class' => 'form-control', 'autofocus']) !!}
                        <span class="text-danger">{{ $errors->first('app_name') }}</span>
                    </div>
                    <div class="form-group mt-3">
                        <lable for="app_email">Email Instansi</lable>
                        {!! Form::text('app_email', settings()->get('app_email'), ['class' => 'form-control']) !!}
                        <span class="text-danger">{{ $errors->first('app_email') }}</span>
                    </div>
                    <div class="form-group mt-3">
                        <lable for="app_phone">Nomor Telphone Instansi</lable>
                        {!! Form::text('app_phone', settings()->get('app_phone'), ['class' => 'form-control']) !!}
                        <span class="text-danger">{{ $errors->first('app_phone') }}</span>
                    </div>
                    <div class="form-group mt-3">
                        <lable for="app_addrress">Alamat Instansi</lable>
                        {!! Form::textarea('app_addrress', settings()->get('app_addrress'), [
                            'class' => 'form-control',
                            'rows' => 3,
                        ]) !!}
                        <span class="text-danger">{{ $errors->first('app_addrress') }}</span>
                    </div>
                    <div class="form-group mt-3">
                        <lable for="app_pagination">data Perhalaman</lable>
                        {!! Form::number('app_pagination', settings()->get('app_pagination'), ['class' => 'form-control']) !!}
                        <span class="text-danger">{{ $errors->first('app_pagination') }}</span>
                    </div>

                    {!! Form::submit('UPDATE', ['class' => 'btn btn-primary mt-3']) !!}
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/operator/user_form.blade.php
@extends('layouts.app_sneat')

@section('content')
    <div class="row justify-content-center">
        <h4 class="fw-bold py-1 mb-4"><span class="text-muted fw-light"><a href="{{ route('wali.index') }}">Data Wali</a> / </span>{{ $title }}</h4>        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    {!! Form::model($model, ['route' => $route, 'method' => $method]) !!}
                    <div class="form-group">
                        <label for="name">Nama</label>
                        {!! Form::text('name', null, ['class' => 'form-control', 'autofocus']) !!}
                        <span class="text-danger">{{ $errors->first('name') }}</span>
                    </div>
                    <div class="form-group mt-3">
                        <label for="email">Email</label>
                        {!! Form::text('email', null, ['class' => 'form-control']) !!}
                        <span class="text-danger">{{ $errors->first('email') }}</span>
                    </div>
                    <div class="form-group mt-3">
                        <label for="nohp">No HP</label>
                        {!! Form::text('nohp', null, ['class' => 'form-control']) !!}
                        <span class="text-danger">{{ $errors->first('nohp') }}</span>
                    </div>
                    @if (\Route::is('user.create'))
                        <div class="form-group mt-3">
                            <label for="akses">Hak Akses</label>
                            {!! Form::select(
                                'akses',
                                [
                                    'operator' => 'Operator Sekolah',
                                    'admin' => 'Administrator',
                                    'wali' => 'Wali Murid',
                                ],
                                null,
                                ['class' => 'form-control'],
                            ) !!}
                            <span class="text-danger">{{ $errors->first('akses') }}</span>
                        </div>
                    @endif
                    <div class="form-group mt-3">
                        <label for="password">Password</label>
                        {!! Form::password('password', ['class' => 'form-control']) !!}
                        <span class="text-danger">{{ $errors->first('password') }}</span>
                    </div>
                    {!! Form::submit($button, ['class' => 'btn btn-primary mt-3']) !!}
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection